server:
  port: 5051
spring:
  datasource:
    initialization-mode: always
    password: admin
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:59853/allshop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
